# fly.toml app configuration file generated for fake-email on 2024-02-27T22:52:23-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'fake-email'
primary_region = 'ord'

[experimental]
  auto_rollback = true

[build]

[env]
  PORT = "8080"

[[services.ports]]
  handlers = ["http"]
  port = 80
  force_https = true

[http_service]
  internal_port = 8080
  internal_address = "0.0.0.0"
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 1
  processes = ["app"]
