name: FrontEnd Pipeline


on:
  push:
    branches:
      - main

jobs:
  backend_job: 
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
        with:          
          python-version: '3.10'
      
      - name: Check directory
        run: |
          cd backend
          pwd
          ls -l
      
      - name: Create venv
        run: |
          cd backend
          python3 -m venv venv
      
      - name: Activate environment
        run: |
          cd backend
          source venv/bin/activate
      
      - name: Install dependencies
        run: |
          cd backend
          pip install -r reqs.txt

      - name: Unittest user
        run: |
          cd backend
          export PYTHONPATH=$(pwd)
          python3 tests/unit_user.py

      - name: Unittest email
        run: |
          cd backend
          export PYTHONPATH=$(pwd)
          python3 tests/unit_email.py
      
      # - name: Start server
        # run: flask run
